version: '3.8'

services:
  app:
    container_name: ETOP_NODE_TMS
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
